version: '2'
services:
  backend:
    build: ./backend
    ports:
      - "3001:3001"
    volumes:
      - ./backend:/code
      - /code/node_modules
    depends_on:
      - db
  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/code
      - /code/node_modules
    depends_on:
      - backend
volumes:
  db_data:
